aiku/build.gradle
aiku/src/main/java/konkuk/aiku/controller/LoginController.java
aiku/src/main/java/konkuk/aiku/controller/UserController.java
aiku/src/main/java/konkuk/aiku/domain/Setting.java
aiku/src/main/java/konkuk/aiku/domain/Users.java
aiku/src/main/java/konkuk/aiku/dto/AccessTokenDTO.java
aiku/src/main/java/konkuk/aiku/dto/RefreshTokenDTO.java
aiku/src/main/java/konkuk/aiku/dto/UserAddDTO.java
aiku/src/main/java/konkuk/aiku/dto/UserSignInDTO.java
aiku/src/main/java/konkuk/aiku/repository/UsersRepository.java
aiku/src/main/java/konkuk/aiku/security/JwtAuthenticationFilter.java
aiku/src/main/java/konkuk/aiku/security/JwtToken.java
aiku/src/main/java/konkuk/aiku/security/JwtTokenProvider.java
aiku/src/main/java/konkuk/aiku/security/SecurityConfig.java
aiku/src/main/java/konkuk/aiku/service/CustomUserDetailsService.java
aiku/src/main/java/konkuk/aiku/service/UserLoginService.java
aiku/src/main/java/konkuk/aiku/service/UserService.java
aiku/src/main/resources/application.yml
aiku/src/test/java/konkuk/aiku/AikuApplicationTests.java
aiku/src/test/java/konkuk/aiku/UserTest.java

로그인 기능 추가
feat/login -> main
JWT 토큰 발급 및 재발급 로직 완료
간단한 유저 생성 기능 추가

로그인 관련 로직

---

aiku/src/main/java/konkuk/aiku/AikuApplication.java
aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/controller/admin/AdminController.java
aiku/src/main/java/konkuk/aiku/controller/dto/GroupResponseDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/UserSimpleResponseDTO.java
aiku/src/main/java/konkuk/aiku/domain/Groups.java
aiku/src/main/java/konkuk/aiku/domain/Setting.java
aiku/src/main/java/konkuk/aiku/domain/TimeEntity.java
aiku/src/main/java/konkuk/aiku/repository/UserGroupRepository.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupDetailServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/LocationServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/SettingServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/UserSimpleServiceDTO.java
aiku/src/main/resources/application.yml
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java
aiku/src/test/resources/application.yml

그룹 관련 기능 추가
feat/lgroup -> main
그룹 등록, 삭제, 수정, 상세 조회, 입장 구현 완료

Feature group

---

aiku/src/main/java/konkuk/aiku/controller/ScheduleController.java
aiku/src/main/java/konkuk/aiku/controller/dto/LocationDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/ScheduleDTO.java
aiku/src/main/java/konkuk/aiku/domain/Groups.java
aiku/src/main/java/konkuk/aiku/domain/Location.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/domain/UserSchedule.java
aiku/src/main/java/konkuk/aiku/exception/NoAthorityToAccessException.java
aiku/src/main/java/konkuk/aiku/repository/UserGroupRepository.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupDetailServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/LocationServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleDetailServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/UserSimpleServiceDTO.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java
aiku/src/test/java/konkuk/aiku/service/ScheduleServiceTest.java
aiku/src/test/resources/application.yml

스케줄 등록
- 성공시 응답 메세지 미구현
- 실패시 응답 메세지 미구현
스케줄 수정
- 성공시 응답 메세지 미구현
- 실패시 응답 메세지 미구현
Users엔티티의 필드 이름 변경(userName -> personName)에 따른 코드 수정

스케줄 등록, 수정 기능 구현

---

aiku/src/main/java/konkuk/aiku/exception/ErrorCode.java
aiku/src/main/java/konkuk/aiku/exception/NoAthorityToAccessException.java
aiku/src/main/java/konkuk/aiku/exception/NoSuchEntityException.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java

NO_SUCH_ENTITY(404, "존재하지 않는 데이터입니다."),
NO_SUCH_SCHEDULE(404, "존재하지 않는 스케줄입니다."),
NO_SUCH_GROUP(404, "존재하지 않는 그룹입니다."),
NO_SUCH_ORDER(404, "존재하지 않는 주문입니다."),
다음과 같이 에러코드를 상세화. 상황에 맞게 추가하여 사용.

ErrorCode 상세화

---

aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/repository/UserGroupRepository.java
aiku/src/main/java/konkuk/aiku/repository/UserGroupRepositoryCustom.java
aiku/src/main/java/konkuk/aiku/repository/UserGroupRepositoryCustomImpl.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java

UserGroupRepository의 findByUserIdAndGroupId, deleteByUserIdAndGroupId메서드의 복잡한 sql문 제거
- UserGroupRepositoryCustom생성
- jpql을 통한 쿼리 생성

GroupService 성능 개선

---

aiku/build.gradle
aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/controller/ScheduleController.java
aiku/src/main/java/konkuk/aiku/controller/dto/ControllerDTOUtils.java
aiku/src/main/java/konkuk/aiku/controller/dto/ScheduleDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/ScheduleResponseDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/ScheduleResultReponseDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/SuccessResponseDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/UserArrivalDataDTO.java
aiku/src/main/java/konkuk/aiku/controller/dto/UserSimpleResponseDTO.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/domain/UserArrivalData.java
aiku/src/main/java/konkuk/aiku/exception/AlreadyInException.java
aiku/src/main/java/konkuk/aiku/exception/ErrorCode.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepository.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepositoryCustom.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepositoryCustomImpl.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleDetailServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleResultServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ScheduleServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/ServiceDTOUtils.java
aiku/src/main/java/konkuk/aiku/service/dto/UserArrivalDataServiceDTO.java
aiku/src/main/java/konkuk/aiku/service/dto/UserSimpleServiceDTO.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java
aiku/src/test/java/konkuk/aiku/service/ScheduleServiceTest.java
aiku/src/test/resources/application.yml

스케줄 기능 추가
- 스케줄 상세 조회
- 스케줄 결과 조회
DTO생성 유틸 클래스 추가
- ConrollerDTOUtil클래스 추가
- ServiceDTOUtil클래스 추가
요청 성공시 응답 메세지 DTO 생성
- SuccessResponseDTO클래스 추가
- SuccessMessage 열거체를 통해 성공 메세지 생성 가능

스케줄 기능 추가, DTO생성 유틸 클래스 추가, 요청 성공시 응답 메세지 DTO 생성

---

aiku/.gitignore
aiku/build.gradle
aiku/src/main/java/konkuk/aiku/controller/AlarmController.java
aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/controller/dto/SuccessResponseDto.java
aiku/src/main/java/konkuk/aiku/domain/Users.java
aiku/src/main/java/konkuk/aiku/exception/ErrorCode.java
aiku/src/main/java/konkuk/aiku/exception/TokenException.java
aiku/src/main/java/konkuk/aiku/firebase/FcmToken.java
aiku/src/main/java/konkuk/aiku/firebase/FcmTokenProvider.java
aiku/src/main/java/konkuk/aiku/firebase/FirebaseInitializer.java
aiku/src/main/java/konkuk/aiku/security/SecurityConfig.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java

Firebase Messeging 
- firebase FCM 토큰 json파일 gitignore에 추가
- 토큰 json파일은 firebase 패키지 아래에 있어야 한다.
알람 fcm 토큰 등록, 업데이트
- 테스트 미구현

Firebase Messeging 설치, 초기화 / FCM 토큰 추가, 업데이트 기능 추가

---

aiku/src/main/java/konkuk/aiku/AikuApplication.java
aiku/src/main/java/konkuk/aiku/controller/AlarmController.java
aiku/src/main/java/konkuk/aiku/controller/dto/EmojiMessageDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/RealTimeLocationDto.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/domain/UserArrivalData.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventHandler.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventPublisher.java
aiku/src/main/java/konkuk/aiku/event/ScheduleUserArrivalEvent.java
aiku/src/main/java/konkuk/aiku/exception/ErrorCode.java
aiku/src/main/java/konkuk/aiku/exception/ExceptionHandlers.java
aiku/src/main/java/konkuk/aiku/exception/MessagingException.java
aiku/src/main/java/konkuk/aiku/firebase/FirebaseInitializer.java
aiku/src/main/java/konkuk/aiku/firebase/MessageSender.java
aiku/src/main/java/konkuk/aiku/firebase/dto/Message.java
aiku/src/main/java/konkuk/aiku/firebase/dto/MessageTitle.java
aiku/src/main/java/konkuk/aiku/firebase/dto/RealTimeLocationMessage.java
aiku/src/main/java/konkuk/aiku/firebase/dto/SendingEmojiMessage.java
aiku/src/main/java/konkuk/aiku/firebase/dto/UserArrivalMessage.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepositoryCustom.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepositoryCustomImpl.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/main/resources/application.yml
aiku/src/test/java/konkuk/aiku/firebase/dto/MessageTest.java
aiku/src/test/java/konkuk/aiku/service/AlarmServiceTest.java
aiku/src/test/java/konkuk/aiku/service/ScheduleServiceTest.java
aiku/src/test/resources/application.yml

실시간 위치 정보 알림 기능 개발
- 유저에게 실시간 위치가 도착하면 firebase에 메세지를 전송하여 스케줄에 속한 유저들에게 알림이 도착하도록 한다.
- 스케줄 목적지의 특정 반경 안에 속할 경우 이벤트를 발생하여 유저 도착 정보 알림을 발생시킨다.

실시간 위치 정보 알림 기능 개발

---

aiku/src/main/java/konkuk/aiku/domain/Groups.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/test/java/konkuk/aiku/service/ScheduleServiceTest.java

수정메서드 추가
- 불필요한 Setter메서드 제거
Groups엔티티를 통해 Schedule 영속
-Groups.addSchedule()

Schedule엔티티 리팩토링

---

aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/controller/dto/GroupDto.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupServiceDto.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java

serviceDto에 추가시 view가 변경시 service패키지를 변경해야 함.
따라서 controllerDto에서 serviceDto를 생성하여 전달.

controllerDto -> serviceDto변환 메서드를 conrollerDto에 추가

---

aiku/src/main/java/konkuk/aiku/controller/ScheduleController.java
aiku/src/main/java/konkuk/aiku/controller/dto/LocationDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/ScheduleDto.java

serviceDto에 추가시 view가 변경시 service패키지를 변경해야 함.
따라서 controllerDto에서 serviceDto를 생성하여 전달.

serviceDto변환 메서드를 conrollerDto에 추가

---

aiku/src/main/java/konkuk/aiku/event/ScheduleAlarmEvent.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventHandler.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventPublisher.java
aiku/src/main/java/konkuk/aiku/event/UserArriveInScheduleEvent.java
aiku/src/main/java/konkuk/aiku/exception/ErrorCode.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java

- 스케줄 하루 전 클라이언트가 예정된 스케줄에 대해 알람을 받을 수 있어야 한다.
- 스케줄 시간이 될 시 클라이언트가 스케줄 이벤트가 열린것을 알람을 통해 알 수 있어야 한다.

스케줄 등록시 스케줄에 대한 알람을 등록하는 이벤트 발생

---

aiku/src/main/java/konkuk/aiku/event/ScheduleEventHandler.java
aiku/src/main/java/konkuk/aiku/firebase/dto/MessageTitle.java
aiku/src/main/java/konkuk/aiku/firebase/dto/ScheduleAlarmMessage.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepository.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java

스케줄 등록시 스케줄 전날, 당일 알람 등록
- ScheduleService에서 스케줄 등록 후 ScheduleAlarmEvent발생.
- 이벤트 핸들러를 통해 스케줄러에 알람 등록
- 스케줄 등록과 알람 발생의 역할을 분리할 수 있다.

스케줄 등록시 스케줄 전날, 당일 알람 등록

---

aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/controller/dto/GroupListResponseDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/GroupSimpleResponseDto.java
aiku/src/main/java/konkuk/aiku/domain/Groups.java
aiku/src/main/java/konkuk/aiku/repository/GroupsRepository.java
aiku/src/main/java/konkuk/aiku/repository/GroupsRepositoryCustom.java
aiku/src/main/java/konkuk/aiku/repository/GroupsRepositoryCustomImpl.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepository.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupListServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupSimpleServiceDto.java
aiku/src/test/java/konkuk/aiku/domain/GroupsTest.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceIntegrationTest.java
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java

그룹 목록 조회 기능 추가
- 단위 테스트 진행 완료
- 통합 테스트 진행 완료

그룹 목록 조회 기능 추가

---

aiku/src/main/java/konkuk/aiku/controller/dto/BettingAddDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/BettingModifyDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/ItemDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/ItemResponseDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/OrderItemSimpleDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/TitleDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/TitleResponseDto.java
aiku/src/main/java/konkuk/aiku/domain/Orders.java
aiku/src/main/java/konkuk/aiku/domain/Title.java
aiku/src/main/java/konkuk/aiku/domain/item/Item.java
aiku/src/main/java/konkuk/aiku/repository/OrdersRepositoryCustom.java
aiku/src/main/java/konkuk/aiku/repository/OrdersRepositoryCustomImpl.java
aiku/src/main/java/konkuk/aiku/service/AdminService.java
aiku/src/main/java/konkuk/aiku/service/BettingService.java
aiku/src/main/java/konkuk/aiku/service/OrderService.java
aiku/src/main/java/konkuk/aiku/service/dto/BettingServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/ItemServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/OrderFindServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/OrderServiceDto.java
aiku/src/test/java/konkuk/aiku/service/AdminServiceTest.java
aiku/src/test/java/konkuk/aiku/service/BettingServiceTest.java
aiku/src/test/java/konkuk/aiku/service/ItemServiceTest.java
aiku/src/test/java/konkuk/aiku/service/OrderServiceTest.java
aiku/src/test/java/konkuk/aiku/service/TitleServiceTest.java

현재는 성공 테스트만 통과 완료
실패 테스트는 이후에 작성 예정입니다!

다른 서비스에 대한 테스트 완료

---

aiku/src/main/java/konkuk/aiku/controller/dto/GroupSimpleResponseDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/UserSimpleResponseDto.java
aiku/src/main/java/konkuk/aiku/domain/Groups.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/exception/AlreadyInException.java
aiku/src/main/java/konkuk/aiku/exception/ExceptionHandlers.java
aiku/src/main/java/konkuk/aiku/exception/MessagingException.java
aiku/src/main/java/konkuk/aiku/exception/NoAthorityToAccessException.java
aiku/src/main/java/konkuk/aiku/exception/NoSuchEntityException.java
aiku/src/main/java/konkuk/aiku/repository/GroupsRepository.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepository.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupDetailServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupScheduleListServiceDto.java
aiku/src/main/java/konkuk/aiku/service/dto/GroupSimpleServiceDto.java
aiku/src/main/resources/application.yml
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java
aiku/src/test/resources/application.yml

[그룹, 스케줄 POSTMAN테스트 진행하며 수정]
1. Groups엔티티에 userCount필드 추가
- db 쿼리 감소를 위한 필드 추가
2. ExceptionHandlers 클래스에 예외 처리 추가
- ErrorDto응답 메세지 전송

Test yoona

---

aiku/src/main/java/konkuk/aiku/controller/AlarmController.java
aiku/src/main/java/konkuk/aiku/controller/dto/EmojiMessageDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/RealTimeLocationDto.java
aiku/src/main/java/konkuk/aiku/controller/dto/UserArrivalDto.java
aiku/src/main/java/konkuk/aiku/domain/EmojiType.java
aiku/src/main/java/konkuk/aiku/domain/Schedule.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventHandler.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEventPublisher.java
aiku/src/main/java/konkuk/aiku/event/UserArriveInScheduleEvent.java
aiku/src/main/java/konkuk/aiku/firebase/dto/RealTimeLocationMessage.java
aiku/src/main/java/konkuk/aiku/firebase/dto/SendingEmojiMessage.java
aiku/src/main/java/konkuk/aiku/firebase/dto/UserArrivalMessage.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java
aiku/src/main/java/konkuk/aiku/service/ScheduleService.java
aiku/src/test/java/konkuk/aiku/firebase/dto/MessageTest.java

유저의 도착 알람 기능 추가, 도착 시 이벤트 발생(베팅 결과, 유저 도착 정보 생성)

Feat alarm

---

aiku/src/main/java/konkuk/aiku/controller/GroupController.java
aiku/src/main/java/konkuk/aiku/repository/GroupsRepository.java
aiku/src/main/java/konkuk/aiku/service/GroupService.java
aiku/src/main/resources/application.yml
aiku/src/test/java/konkuk/aiku/service/GroupServiceTest.java
aiku/src/test/resources/application.yml

Group관련 기능 jpa 성능 개선
- default_batch_fetch_size설정

Group관련 기능 jpa 성능 개선

---

aiku/src/main/java/konkuk/aiku/domain/Users.java
aiku/src/main/java/konkuk/aiku/event/BettingEventHandler.java
aiku/src/main/java/konkuk/aiku/event/BettingEventPublisher.java
aiku/src/main/java/konkuk/aiku/event/ScheduleEndEvent.java
aiku/src/main/java/konkuk/aiku/event/TitleProvideEvent.java
aiku/src/main/java/konkuk/aiku/event/TitleProvideEventHandler.java
aiku/src/main/java/konkuk/aiku/event/TitleProvideEventPublisher.java
aiku/src/main/java/konkuk/aiku/repository/BettingRepository.java
aiku/src/main/java/konkuk/aiku/repository/ScheduleRepository.java
aiku/src/main/java/konkuk/aiku/repository/TitleRepository.java
aiku/src/main/java/konkuk/aiku/service/TitleProviderService.java

칭호 이름은 어떻게 해야 할지 모르겠어서 일단 임시로 두었습니다.
메시지를 보내야 하는 부분은 비워두었습니다.
확인 부탁드립니다!

칭호 생성 로직 작성

---

aiku/src/main/java/konkuk/aiku/exception/ExceptionHandlers.java
aiku/src/main/java/konkuk/aiku/filter/FilterConfig.java
aiku/src/main/java/konkuk/aiku/filter/LogFilter.java
aiku/src/main/java/konkuk/aiku/filter/LogIntercepter.java
aiku/src/main/java/konkuk/aiku/firebase/FcmToken.java
aiku/src/main/java/konkuk/aiku/firebase/FcmTokenProvider.java
aiku/src/main/java/konkuk/aiku/security/JwtAuthenticationFilter.java
aiku/src/main/java/konkuk/aiku/service/AlarmService.java
aiku/src/main/resources/application.yml
aiku/src/main/resources/logback-spring.xml
aiku/src/test/java/konkuk/aiku/service/AdminServiceTest.java
aiku/src/test/java/konkuk/aiku/service/BettingServiceTest.java

이벤트 핸들러의 Asyn을 통한 스레드 분리는 아직 적용되지 않음

MDC를 통한 다중 스레드 로깅 적용

---

aiku/src/main/java/konkuk/aiku/controller/Ec2TestController.java
aiku/src/main/java/konkuk/aiku/firebase/FirebaseInitializer.java
aiku/src/main/java/konkuk/aiku/firebase/MessageSender.java
aiku/src/main/java/konkuk/aiku/firebase/dto/RealTimeLocationMessage.java
aiku/src/main/java/konkuk/aiku/firebase/dto/UserArrivalMessage.java
aiku/src/main/java/konkuk/aiku/security/SecurityConfig.java
aiku/src/main/resources/application.yml
aiku/src/main/resources/logback-spring.xml
aiku/src/test/resources/application.yml

aws 로드밸런싱의 상태검사를 위한 controller 추가
ec2를 위한 설정 변경 (local에서 실행시 다시 변경해야함)
- FirebaseInitialization의 토큰 json 파일 경로
- application.yml 설정 정보

aws 로드밸런싱의 상태검사를 위한 controller 추가 
